//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaStokTakipSistemi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataContext2 : DbContext
    {
        public DataContext2()
            : base("name=DataContext2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DemirbasDepartman> DemirbasDepartmen { get; set; }
        public virtual DbSet<Demirbaslar> Demirbaslars { get; set; }
        public virtual DbSet<Departmanlar> Departmanlars { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<KullaniciRol> KullaniciRols { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
        public virtual DbSet<Roller> Rollers { get; set; }
        public virtual DbSet<Sirketler> Sirketlers { get; set; }
        public virtual DbSet<Urun_Stok> Urun_Stok { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<Zimmetler> Zimmetlers { get; set; }
        public virtual DbSet<PersonelDepartman> PersonelDepartmen { get; set; }
    
        public virtual int sp_DemirbasDuzenle(Nullable<int> demirbasNo, Nullable<int> sirketid, Nullable<int> departmanId, Nullable<int> demirbasAdedi, string demirbasOzellikleri)
        {
            var demirbasNoParameter = demirbasNo.HasValue ?
                new ObjectParameter("demirbasNo", demirbasNo) :
                new ObjectParameter("demirbasNo", typeof(int));
    
            var sirketidParameter = sirketid.HasValue ?
                new ObjectParameter("sirketid", sirketid) :
                new ObjectParameter("sirketid", typeof(int));
    
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("departmanId", departmanId) :
                new ObjectParameter("departmanId", typeof(int));
    
            var demirbasAdediParameter = demirbasAdedi.HasValue ?
                new ObjectParameter("demirbasAdedi", demirbasAdedi) :
                new ObjectParameter("demirbasAdedi", typeof(int));
    
            var demirbasOzellikleriParameter = demirbasOzellikleri != null ?
                new ObjectParameter("demirbasOzellikleri", demirbasOzellikleri) :
                new ObjectParameter("demirbasOzellikleri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DemirbasDuzenle", demirbasNoParameter, sirketidParameter, departmanIdParameter, demirbasAdediParameter, demirbasOzellikleriParameter);
        }
    
        public virtual int sp_DemirbasEkle(Nullable<int> departmanId, Nullable<int> sirketid, Nullable<int> urunId, Nullable<int> demirbasAdedi, string demirbasOzellikler)
        {
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("departmanId", departmanId) :
                new ObjectParameter("departmanId", typeof(int));
    
            var sirketidParameter = sirketid.HasValue ?
                new ObjectParameter("sirketid", sirketid) :
                new ObjectParameter("sirketid", typeof(int));
    
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            var demirbasAdediParameter = demirbasAdedi.HasValue ?
                new ObjectParameter("demirbasAdedi", demirbasAdedi) :
                new ObjectParameter("demirbasAdedi", typeof(int));
    
            var demirbasOzelliklerParameter = demirbasOzellikler != null ?
                new ObjectParameter("demirbasOzellikler", demirbasOzellikler) :
                new ObjectParameter("demirbasOzellikler", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DemirbasEkle", departmanIdParameter, sirketidParameter, urunIdParameter, demirbasAdediParameter, demirbasOzelliklerParameter);
        }
    
        public virtual ObjectResult<sp_Deparmandaki_Demirbaslar01_Result> sp_Deparmandaki_Demirbaslar01(Nullable<int> departmanId)
        {
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("DepartmanId", departmanId) :
                new ObjectParameter("DepartmanId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Deparmandaki_Demirbaslar01_Result>("sp_Deparmandaki_Demirbaslar01", departmanIdParameter);
        }
    
        public virtual int sp_DepartmanaDemirbasEkle(Nullable<int> demirbasId, Nullable<int> departmanId, Nullable<int> adet)
        {
            var demirbasIdParameter = demirbasId.HasValue ?
                new ObjectParameter("DemirbasId", demirbasId) :
                new ObjectParameter("DemirbasId", typeof(int));
    
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("DepartmanId", departmanId) :
                new ObjectParameter("DepartmanId", typeof(int));
    
            var adetParameter = adet.HasValue ?
                new ObjectParameter("Adet", adet) :
                new ObjectParameter("Adet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepartmanaDemirbasEkle", demirbasIdParameter, departmanIdParameter, adetParameter);
        }
    
        public virtual ObjectResult<sp_Departmandaki_Demirbaslar02_Result> sp_Departmandaki_Demirbaslar02(Nullable<int> departmanId)
        {
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("DepartmanId", departmanId) :
                new ObjectParameter("DepartmanId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Departmandaki_Demirbaslar02_Result>("sp_Departmandaki_Demirbaslar02", departmanIdParameter);
        }
    
        public virtual int sp_DepartmanEkle(string departmanAdi, Nullable<int> sirketId)
        {
            var departmanAdiParameter = departmanAdi != null ?
                new ObjectParameter("DepartmanAdi", departmanAdi) :
                new ObjectParameter("DepartmanAdi", typeof(string));
    
            var sirketIdParameter = sirketId.HasValue ?
                new ObjectParameter("SirketId", sirketId) :
                new ObjectParameter("SirketId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepartmanEkle", departmanAdiParameter, sirketIdParameter);
        }
    
        public virtual int sp_DepartmanGuncelle(Nullable<int> departmanId, string departmanAdi, Nullable<int> personelId)
        {
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("DepartmanId", departmanId) :
                new ObjectParameter("DepartmanId", typeof(int));
    
            var departmanAdiParameter = departmanAdi != null ?
                new ObjectParameter("DepartmanAdi", departmanAdi) :
                new ObjectParameter("DepartmanAdi", typeof(string));
    
            var personelIdParameter = personelId.HasValue ?
                new ObjectParameter("PersonelId", personelId) :
                new ObjectParameter("PersonelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepartmanGuncelle", departmanIdParameter, departmanAdiParameter, personelIdParameter);
        }
    
        public virtual ObjectResult<sp_personel_Demirbaslar_Result> sp_personel_Demirbaslar(Nullable<int> personelId)
        {
            var personelIdParameter = personelId.HasValue ?
                new ObjectParameter("PersonelId", personelId) :
                new ObjectParameter("PersonelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_personel_Demirbaslar_Result>("sp_personel_Demirbaslar", personelIdParameter);
        }
    
        public virtual ObjectResult<sp_personel_Demirbaslar1_Result> sp_personel_Demirbaslar1(Nullable<int> personelId)
        {
            var personelIdParameter = personelId.HasValue ?
                new ObjectParameter("PersonelId", personelId) :
                new ObjectParameter("PersonelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_personel_Demirbaslar1_Result>("sp_personel_Demirbaslar1", personelIdParameter);
        }
    
        public virtual int sp_PersonelEkle(string personelSoyad)
        {
            var personelSoyadParameter = personelSoyad != null ?
                new ObjectParameter("personelSoyad", personelSoyad) :
                new ObjectParameter("personelSoyad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PersonelEkle", personelSoyadParameter);
        }
    
        public virtual int sp_UrunEkle(string urunAdi, Nullable<decimal> urunBirimFiyati, Nullable<int> stok, Nullable<System.DateTime> satinAlinmaTarihi, Nullable<decimal> urunToptanFiyati, string satinAlinilanKurum)
        {
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            var urunBirimFiyatiParameter = urunBirimFiyati.HasValue ?
                new ObjectParameter("UrunBirimFiyati", urunBirimFiyati) :
                new ObjectParameter("UrunBirimFiyati", typeof(decimal));
    
            var stokParameter = stok.HasValue ?
                new ObjectParameter("Stok", stok) :
                new ObjectParameter("Stok", typeof(int));
    
            var satinAlinmaTarihiParameter = satinAlinmaTarihi.HasValue ?
                new ObjectParameter("SatinAlinmaTarihi", satinAlinmaTarihi) :
                new ObjectParameter("SatinAlinmaTarihi", typeof(System.DateTime));
    
            var urunToptanFiyatiParameter = urunToptanFiyati.HasValue ?
                new ObjectParameter("UrunToptanFiyati", urunToptanFiyati) :
                new ObjectParameter("UrunToptanFiyati", typeof(decimal));
    
            var satinAlinilanKurumParameter = satinAlinilanKurum != null ?
                new ObjectParameter("SatinAlinilanKurum", satinAlinilanKurum) :
                new ObjectParameter("SatinAlinilanKurum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UrunEkle", urunAdiParameter, urunBirimFiyatiParameter, stokParameter, satinAlinmaTarihiParameter, urunToptanFiyatiParameter, satinAlinilanKurumParameter);
        }
    
        public virtual int sp_UrunGuncelle(Nullable<int> urunId, string urunAdi, Nullable<decimal> urunBirimFiyati, Nullable<int> stok, Nullable<System.DateTime> satinAlinmaTarihi, Nullable<decimal> urunToptanFiyati, string satinAlinilanKurum)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("UrunId", urunId) :
                new ObjectParameter("UrunId", typeof(int));
    
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            var urunBirimFiyatiParameter = urunBirimFiyati.HasValue ?
                new ObjectParameter("UrunBirimFiyati", urunBirimFiyati) :
                new ObjectParameter("UrunBirimFiyati", typeof(decimal));
    
            var stokParameter = stok.HasValue ?
                new ObjectParameter("Stok", stok) :
                new ObjectParameter("Stok", typeof(int));
    
            var satinAlinmaTarihiParameter = satinAlinmaTarihi.HasValue ?
                new ObjectParameter("SatinAlinmaTarihi", satinAlinmaTarihi) :
                new ObjectParameter("SatinAlinmaTarihi", typeof(System.DateTime));
    
            var urunToptanFiyatiParameter = urunToptanFiyati.HasValue ?
                new ObjectParameter("UrunToptanFiyati", urunToptanFiyati) :
                new ObjectParameter("UrunToptanFiyati", typeof(decimal));
    
            var satinAlinilanKurumParameter = satinAlinilanKurum != null ?
                new ObjectParameter("SatinAlinilanKurum", satinAlinilanKurum) :
                new ObjectParameter("SatinAlinilanKurum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UrunGuncelle", urunIdParameter, urunAdiParameter, urunBirimFiyatiParameter, stokParameter, satinAlinmaTarihiParameter, urunToptanFiyatiParameter, satinAlinilanKurumParameter);
        }
    }
}
