//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaStokTakipSistemi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirketler
    {
        public int SirketId { get; set; }
        public string SirketAdi { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
    }
}
