//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaStokTakipSistemi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zimmetler()
        {
            this.DemirbasDepartmen = new HashSet<DemirbasDepartman>();
        }
    
        public int ZimmetId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> DepartmanId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemirbasDepartman> DemirbasDepartmen { get; set; }
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
